# Generated by Django 3.2.9 on 2021-12-09 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_referral'),
    ]

    operations = [
        migrations.AlterField(
            model_name='referral',
            name='code',
            field=models.CharField(blank=True, max_length=8),
        ),
    ]
